env:
  blueprints:
    - name: skeleton
      description: Skeleton
      components:
        - type: position
          entity: 0
          data:
            x: 0
            y: 0
        - type: graphic
          data:
            name: "SkeletonMoveDown1"
    - name: follow
      description: follows the cursor
      components:
        - type: follow
          entity: 0
          data:
            x: 0
            y: 0
  components:
    position:
      type: position
      entity: 0
      data:
        x: 0
        y: 0
    graphic:
      type: graphic
      entity: 0
      data:
        name: ""
    follow:
      type: follow
      entity: 0
      data:
        x: 0
        y: 0

triggers:
  game.created:
    - command: blueprint.create.entity
      vars:
        entity$: env.CreateEntity()
        x: 100
        y: 100
        graphicName: "SkeletonMoveDown1"
        position$: env.components.position
        graphic$: env.components.graphic
      set:
        # Set position
        - path: vars.position.entity
          value: vars.entity
        - path: vars.position.data.x
          value: vars.x
        - path: vars.position.data.y
          value: vars.y
        # Set graphic
        - path: vars.graphic.entity
          value: vars.entity
        - path: vars.graphic.data.name
          value: vars.graphicName
      mapping:
        components$: "[vars.position, vars.graphic]"

    - command: blueprint.create.entity
      vars:
        entity$: env.CreateEntity()
        x: 150
        y: 150
        graphicName: "SkeletonMoveDown1"
        position$: env.components.position
        graphic$: env.components.graphic
        follow$: env.components.follow
      set:
        # Set position
        - path: vars.position.entity
          value: vars.entity
        - path: vars.position.data.x
          value: vars.x
        - path: vars.position.data.y
          value: vars.y
        # Set graphic
        - path: vars.graphic.entity
          value: vars.entity
        - path: vars.graphic.data.name
          value: vars.graphicName
        # Set follow
        - path: vars.follow.entity
          value: vars.entity
        - path: vars.follow.data.x
          value: vars.x
        - path: vars.follow.data.y
          value: vars.y
      mapping:
        components$: "[vars.position, vars.graphic, vars.follow]"

  game.updated:
    - command: graphics.sort
      mapping:
        graphicComponents$: env.ListComponents('graphic')

    - command: blueprint.update.entity
      vars:
        pressedUp$: env.KeyPressed('up') || env.KeyPressed('w')
        pressedDown$: env.KeyPressed('down') || env.KeyPressed('s')
        pressedLeft$: env.KeyPressed('left') || env.KeyPressed('a')
        pressedRight$: env.KeyPressed('right') || env.KeyPressed('d')
        pos$: first(env.ListComponents('position'))
        spd: 2 # speed
      condition: vars.pos != nil && (vars.pressedUp ||vars. pressedDown || vars.pressedLeft || vars.pressedRight)
      mapping:
        components:
          - id$: vars.pos.ID
            type: position
            entity$: vars.pos.Entity
            data:
              x$: "let left = vars.pressedLeft ? vars.spd : 0; let right = vars.pressedRight ? vars.spd : 0; vars.pos.Data.X + right - left"
              y$: "let up = vars.pressedUp ? vars.spd : 0; let down = vars.pressedDown ? vars.spd : 0; vars.pos.Data.Y + down - up"

    - command: follow.move-towards-target
      vars:
        entities$: map(env.ListComponents('follow'), {.Entity})
      condition: len(vars.entities) > 0
      mapping:
        entities$: vars.entities

  game.input.cursor:
    - command: follow.set-target
      vars:
        entities$: map(env.ListComponents('follow'), {.Entity})
      condition: len(vars.entities) > 0
      mapping:
        entities$: vars.entities
        x$: env.cursor.x
        y$: env.cursor.y

    - command: blueprint.create.entity
      vars:
        entity$: env.CreateEntity()
        components$: find(env.blueprints, .name == 'skeleton').components
        x$: env.cursor.x
        y$: env.cursor.y
      set:
        - path: vars.components[0].data.x
          value: vars.x
        - path: vars.components[0].data.y
          value: vars.y
        - path: vars.components[*].entity
          value: vars.entity
      mapping:
        components$: vars.components

  game.draw:
    - command: render
      condition: true
      mapping:
        screen$: env.screen
        components$: sortBy(env.ListComponents('graphic'), {.Data.Layer}, "desc")
