triggers:
  game.created:
    - command: blueprint.create.entity
      condition:
      params:
        components:
          - type: position
            entity$: CreateEntity()
            data:
              x$: 10 + 10
              y: 10
  
    - command: blueprint.create.entity
      condition:
      include:
        entity$: CreateEntity()
      params:
        components:
          - type: position
            entity$: entity
            data:
              x: 50
              y: 50
          - type: follow
            entity$: entity
            data:
              x: 50
              y: 50

  game.updated:
    - command: blueprint.update.entity
      include:
        pressedUp$: KeyPressed('up') || KeyPressed('w')
        pressedDown$: KeyPressed('down') || KeyPressed('s')
        pressedLeft$: KeyPressed('left') || KeyPressed('a')
        pressedRight$: KeyPressed('right') || KeyPressed('d')
        pos$: first(ListComponents('position'))
      condition: pos != nil && (pressedUp || pressedDown || pressedLeft || pressedRight)
      params:
        components:
          - id$: pos.ID
            type: position
            entity$: pos.Entity
            data:
              x$: "let left = pressedLeft ? 1 : 0; let right = pressedRight ? 1 : 0; pos.Data.X + right - left"
              y$: "let up = pressedUp ? 1 : 0; let down = pressedDown ? 1 : 0; pos.Data.Y + down - up"

    - command: follow.move-towards-target
      include:
        entities$: map(ListComponents('follow'), {.Entity})
      condition: len(entities) > 0
      params:
        entities$: entities

  game.input.cursor:
    - command: follow.set-target
      include:
        entities$: map(ListComponents('follow'), {.Entity})
      condition: len(entities) > 0
      params:
        entities$: entities
        X$: cursor.X
        Y$: cursor.Y
