// Code generated by "stringer -type=Direction"; DO NOT EDIT.

package direction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[North-1]
	_ = x[South-2]
	_ = x[West-3]
	_ = x[East-4]
	_ = x[NorthWest-5]
	_ = x[NorthEast-6]
	_ = x[SouthWest-7]
	_ = x[SouthEast-8]
}

const _Direction_name = "NoneNorthSouthWestEastNorthWestNorthEastSouthWestSouthEast"

var _Direction_index = [...]uint8{0, 4, 9, 14, 18, 22, 31, 40, 49, 58}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
